"""empty message

Revision ID: 22fec128c78e
Revises: 
Create Date: 2022-03-11 08:03:23.587456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22fec128c78e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('promos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=180), nullable=True),
    sa.Column('description', sa.String(length=5000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_promos_id'), 'promos', ['id'], unique=False)
    op.create_table('participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=180), nullable=True),
    sa.Column('promo_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['promo_id'], ['promos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_participants_id'), 'participants', ['id'], unique=False)
    op.create_table('prizes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=5000), nullable=True),
    sa.Column('promo_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['promo_id'], ['promos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prizes_id'), 'prizes', ['id'], unique=False)
    op.create_table('results',
    sa.Column('winner', sa.Integer(), nullable=False),
    sa.Column('prize', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['prize'], ['prizes.id'], ),
    sa.ForeignKeyConstraint(['winner'], ['participants.id'], ),
    sa.PrimaryKeyConstraint('winner', 'prize')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('results')
    op.drop_index(op.f('ix_prizes_id'), table_name='prizes')
    op.drop_table('prizes')
    op.drop_index(op.f('ix_participants_id'), table_name='participants')
    op.drop_table('participants')
    op.drop_index(op.f('ix_promos_id'), table_name='promos')
    op.drop_table('promos')
    # ### end Alembic commands ###
